name: Install Nginx on Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  install_nginx:
    runs-on: self-hosted

    steps:
      - name: Install Nginx
        run: |
          sudo apt-get update && sudo apt-get install nginx
